package com.beiyelin.service.footstone.model;

import java.util.Date;
import java.util.List;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String userName;

    private String userNumber;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean emailActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean phoneActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date auditDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean audited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String frontImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String backImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date durDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String enFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String enLastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.ID
     *
     * @return the value of fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.ID
     *
     * @param id the value for fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UserType
     *
     * @return the value of fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UserType
     *
     * @param userType the value for fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UserName
     *
     * @return the value of fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UserName
     *
     * @param userName the value for fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.TrueName
     *
     * @return the value of fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.TrueName
     *
     * @param trueName the value for fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.NickName
     *
     * @return the value of fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.NickName
     *
     * @param nickName the value for fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Sex
     *
     * @return the value of fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Sex
     *
     * @param sex the value for fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.EmployeeID
     *
     * @return the value of fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.EmployeeID
     *
     * @param employeeId the value for fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.DepartmentID
     *
     * @return the value of fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.DepartmentID
     *
     * @param departmentId the value for fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.CreateTime
     *
     * @return the value of fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.CreateTime
     *
     * @param createTime the value for fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Password
     *
     * @return the value of fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Password
     *
     * @param password the value for fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Salt
     *
     * @return the value of fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Salt
     *
     * @param salt the value for fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Activity
     *
     * @return the value of fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Activity
     *
     * @param activity the value for fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.EmailActivity
     *
     * @return the value of fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getEmailActivity() {
        return emailActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.EmailActivity
     *
     * @param emailActivity the value for fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmailActivity(Boolean emailActivity) {
        this.emailActivity = emailActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.PhoneActivity
     *
     * @return the value of fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getPhoneActivity() {
        return phoneActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.PhoneActivity
     *
     * @param phoneActivity the value for fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPhoneActivity(Boolean phoneActivity) {
        this.phoneActivity = phoneActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Email
     *
     * @return the value of fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Email
     *
     * @param email the value for fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Phone
     *
     * @return the value of fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Phone
     *
     * @param phone the value for fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Status
     *
     * @return the value of fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Status
     *
     * @param status the value for fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UpdateTime
     *
     * @return the value of fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UpdateTime
     *
     * @param updateTime the value for fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Updater
     *
     * @return the value of fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Updater
     *
     * @param updater the value for fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.AuditDate
     *
     * @return the value of fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.AuditDate
     *
     * @param auditDate the value for fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Audited
     *
     * @return the value of fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getAudited() {
        return audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Audited
     *
     * @param audited the value for fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAudited(Boolean audited) {
        this.audited = audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Type
     *
     * @return the value of fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Type
     *
     * @param type the value for fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Number
     *
     * @return the value of fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Number
     *
     * @param number the value for fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.FrontImage
     *
     * @return the value of fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getFrontImage() {
        return frontImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.FrontImage
     *
     * @param frontImage the value for fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setFrontImage(String frontImage) {
        this.frontImage = frontImage == null ? null : frontImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.BackImage
     *
     * @return the value of fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBackImage() {
        return backImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.BackImage
     *
     * @param backImage the value for fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBackImage(String backImage) {
        this.backImage = backImage == null ? null : backImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.DurDate
     *
     * @return the value of fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getDurDate() {
        return durDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.DurDate
     *
     * @param durDate the value for fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setDurDate(Date durDate) {
        this.durDate = durDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.enFirstName
     *
     * @return the value of fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEnFirstName() {
        return enFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.enFirstName
     *
     * @param enFirstName the value for fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEnFirstName(String enFirstName) {
        this.enFirstName = enFirstName == null ? null : enFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.enLastName
     *
     * @return the value of fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEnLastName() {
        return enLastName;
    }

    public String getUserNumber() {
        return userNumber;
    }

    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.enLastName
     *
     * @param enLastName the value for fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */

    public void setEnLastName(String enLastName) {
        this.enLastName = enLastName == null ? null : enLastName.trim();
    }
    
    private List<Role> roleList;
    private List<Permission> permissionList;

	public List<Role> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Role> roleList) {
		this.roleList = roleList;
	}

	public List<Permission> getPermissionList() {
		return permissionList;
	}

	public void setPermissionList(List<Permission> permissionList) {
		this.permissionList = permissionList;
	}
    
}